name: Ofuscar HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Instalar dependencias
      run: npm install uglify-js
    - name: Ofuscar HTML
      run: uglifyjs index.html -o index.min.html
